# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments

# Clean and don't fail
install:
  - rm -rf docs || exit 0

# Build the website
script:
  - binaries/hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  edge:
    branch: gh-pages
  skip_cleanup: true
  local_dir: docs
  github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
